### PR TITLE
Fix menu error

### PR DESCRIPTION
**Pull request by kamekazz**
I apologize if I did anything wrong I have never done any work together for anybody, and I'm new with code. So if I did anything wrong, please let me know. It'll help me out in the future.

### CODE REVIEW

**Review by callbacc — APPROVED** [review]

**Comment by kamekazz** [comment]
I added some responsive for mobile use on some of the pages. I had a couple of questions, and it'll be a lot easier to answer if you accept me on discord. I know I started calling, but I'm baffled what your artwork. I hope you like it. And I was wondering if I can use redux on this project?

**Comment by callbacc** [comment]
you can join our discord server @ https://discord.gg/ZT7f5HtTYP or add me on discord @ Matei Computadores#5750

**Comment by IanWalston** [comment]
thanks  @kamekazz , I'm reviewing this now.

it looks like you branched off main. theres a lot of recent development on the `develop` branch that hasn't been merged in yet, but that should be fine.  I'll merge dev into this branch and switch the target to dev

if this PR was just the bugfix described by the title then it would definitely make it in, and I see that bugfix as part of the PR - but theres also a bunch of other changes to layout and stuff. If it all works I will accept the PR, but theres a good chance it won't work after merging and the PR will be rejected. 

You should try making smaller, targeted PRs that focus on a single issue. And make sure you branch off dev.

We're happy you're making PRs and want you to keep contributing so let us know if theres anything else we can help you with.

**Comment by IanWalston** [comment]
oh wow, this all looks great. I'll merge it with main and I'll handle merging in from develop. great job @kamekazz

**Pull request merged**
